# Generated by Django 4.1 on 2022-09-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiller', '0002_alter_profil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='foto',
        ),
    ]
